### ISSUE TITLE
看作者简书文章了，想问下这种头文件怎么生成

### ISSUE THREAD

**Issue by QingMings** [zyao89/KotlinJS-Vue#1]
像一些成熟的js库，比如Electron 啦，Threejs 啦，

**Comment by zyao89** [comment]
一般都是靠自己定义的，我这个头就是自己写的😂

**Comment by QingMings** [comment]
看到有个项目[ts2kt](https://github.com/Kotlin/ts2kt)   可以把 typescript 的 definition files 生成，不过目前bug一堆。。。（ps:TypeScript 的 definition files 也是手写的？ 哎呦我去，神坑）

**Comment by zyao89** [comment]
ts转起来应该比js方便多了。
